services:
  os-jel:
    image: crisalidesr/crisalid-vocab-search:os-jel-latest
    container_name: os-jel
    expose:
      - "9200"
    # only if you want to access from host machine
    # ports: [ "9200:9200" ]
    networks: [ crisalid-vocab-search-net ]

  os-acm:
    image: crisalidesr/crisalid-vocab-search:os-acm-latest
    container_name: os-acm
    expose:
      - "9200"
    # only if you want to access from host machine
    # ports: [ "9200:9200" ]
    networks: [ crisalid-vocab-search-net ]

  os-aat:
    image: crisalidesr/crisalid-vocab-search:os-aat-latest
    container_name: os-aat
    expose:
      - "9200"
    # only if you want to access from host machine
    # ports: [ "9200:9200" ]
    networks: [ crisalid-vocab-search-net ]

  api:
    image: crisalidesr/crisalid-vocab-search:api-latest
    ports: [ "8000:8000" ]
    depends_on: [ os-jel , os-acm , os-aat ]
    networks: [ crisalid-vocab-search-net ]

networks:
  crisalid-vocab-search-net:
    driver: bridge
