services:
  os:
    #image: crisalidesr/crisalid-vocab-search:os-latest
    image: crisalid-vocab-search:os-local
    container_name: os-1.0
    expose:
      - "9200"
    # only if you want to access from host machine
    #ports: [ "9200:9200" ]
    # override the default heap if needed
    #environment:
    #  OPENSEARCH_JAVA_OPTS: "-Xms2g -Xmx2g"
    networks: [ crisalid-vocab-search-net ]

  api:
    #image: crisalidesr/crisalid-vocab-search:api-1.0
    image: crisalid-vocab-search:api-local

    # docker build -t crisalid-vocab-search:api-local-dev .
    ports: [ "8000:8000" ]
    environment:
      API_VERSION: v1
    depends_on: [ os ]
    networks: [ crisalid-vocab-search-net ]

networks:
  crisalid-vocab-search-net:
    driver: bridge
