[project]
name = "crisalid-vocab-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pylint>=3.3.8",
    "rdflib>=7.1.4",
]
