vocabularies:
  # JEL — local dev (container mapped to 9200)
  - identifier: jel
    type: local_os
    config:
      host: http://os-jel
      port: 9200

  - identifier: mesh
    type: local_os
    config:
      host: http://os-mesh
      port: 9200

  - identifier: acm
    type: local_os
    config:
      host: http://os-acm
      port: 9200

  - identifier: aat
    type: local_os
    config:
      host: http://os-aat
      port: 9200

  - identifier: elsst
    type: local_os
    config:
      host: http://os-elsst
      port: 9200

  - identifier: pactols
    type: local_os
    config:
      host: http://os-pactols
      port: 9200

  - identifier: euroscivoc
    type: local_os
    config:
      host: http://os-euroscivoc
      port: 9200
